services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./app/db/.env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-fastapi-nginx-jupyter-network
  fastapi:
    image: tyamadabiodataeng/fastapi-dev
    container_name: fastapi
    build: 
      context: ./app
      args:
        REQ_DIR: "requirements"
        REQ_TXT: "dev.txt"
    environment:
      - DEBUG=True
    command: uvicorn main:app --host=0.0.0.0 --port=8000 --reload
    volumes:
      - ./app:/usr/src/app/
    expose:
      - "8000"
    depends_on:
      - postgres
    networks:
      - postgres-fastapi-nginx-jupyter-network
  nginx:
    image: tyamadabiodataeng/fastapi-nginx
    container_name: nginx
    build: ./nginx
    volumes:
      - ./app/static:/usr/src/app/static
      - ./app/media:/usr/src/app/media
    ports:
      - "80:80"
    depends_on:
      - fastapi
    networks:
      - postgres-fastapi-nginx-jupyter-network
  jupyter:
    build: 
      context: ./notebooks
      dockerfile: Dockerfile
      args:
        DIR_WORK: "/usr/src/notebooks"
        ENV_YML: "environment.yaml"
        VENV: "bioinfo"
        REQ_TXT: "requirements.txt"
    image: tyamadabiodataeng/fastapi-jupyter
    container_name: jupyter
    command: mamba run --name bioinfo jupyter lab --ip=0.0.0.0 --allow-root --LabApp.token=''
    ports:
     - "8888:8888"
    volumes:
     - .:/usr/src
    tty: true
    stdin_open: true
    depends_on:
      - nginx
    networks:
      - postgres-fastapi-nginx-jupyter-network

networks:
  postgres-fastapi-nginx-jupyter-network:
    driver: bridge

volumes:
  postgres_data:
